### ISSUE TITLE
[BUG]  "Create a server" modal does not follow the theme's design

### ISSUE THREAD

**Issue by ytcalifax** [schnensch0/zelk#36]
**Describe the bug**
The "Create a server" modal does not follow the theme's design - it is completely white when the rest of my zelk theme is using the "Blue Dark" color.

**To Reproduce**
1. Go to the bottom of the server list
2. Click on the '+' icon
3. The modal is white and not "Blue Dark"

**Screenshots**
![image](https://user-images.githubusercontent.com/15365857/162900709-58a65dd2-2b44-4587-82ad-0ba544d56485.png)

**Setup**
 - OS: Windows 11 (22H2)
 - Client Mod: PowerCord
 - Release Channel: canary
 - Enabled Themes: zelk
 - Enabled Plugins: CanaryLinks,PinDMS, Report Messages, Unindent
 - Custom CSS: NO
 - Discord Language: English

**Comment by ytcalifax** [comment]
Reopening, since the statement about the modal not being recolorable is wrong,

**Comment by schnensch0** [comment]
I'd have to sacrifice light mode

**Comment by ytcalifax** [comment]
From what I see in the CSS the theme I gave as an example, there exist selectors for both modes, or am I mistaken?:
![image](https://user-images.githubusercontent.com/15365857/163550636-12a4ca58-a52e-4d5e-a9f2-3e524ef090a8.png)

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
dark discord doesn't support light mode
the problem is that the modal has a `theme-light` class, so the light mode variables are used
you can paste this in your console to remove the class
```js
document.querySelector('.theme-light').classList.remove('theme-light')
```
if you really can't cope with it you could make a plugin with the above code to automatically remove the class

**Comment by schnensch0** [comment]
wtf just happened

**Comment by schnensch0** [comment]
wtf just happened

**Comment by schnensch0** [comment]
wtf just happened

**Comment by schnensch0** [comment]
wtf just happened

**Comment by schnensch0** [comment]
wtf just happened

**Comment by ytcalifax** [comment]
Wow WTF 😂
